/// Coercion of loosely-typed inputs (dates, ratings, states) into the model
/// types, with JavaScript's parsing rules preserved.
library;

import 'error.dart';
import 'models.dart';

/// Converts date/rating/state inputs, matching `TypeConvert` in ts-fsrs.
abstract final class TypeConvert {
  /// Normalizes a card by copying it, so callers cannot mutate the scheduler's
  /// working copy after the fact.
  static Card card(Card card) => card.copy();

  /// Accepts a [Rating], its integer encoding, or its name (case-insensitive).
  static Rating rating(Object? value) {
    if (value is Rating) return value;
    if (value is String) {
      final normalized = value.isEmpty
          ? value
          : value[0].toUpperCase() + value.substring(1).toLowerCase();
      for (final candidate in Rating.values) {
        if (candidate.label == normalized) return candidate;
      }
      throw FSRSValidationError('Invalid rating:[$value]');
    }
    if (value is num) return Rating.fromValue(value.toInt());
    throw FSRSValidationError('Invalid rating:[$value]');
  }

  /// Accepts a [State], its integer encoding, or its name (case-insensitive).
  static State state(Object? value) {
    if (value is State) return value;
    if (value is String) {
      final normalized = value.isEmpty
          ? value
          : value[0].toUpperCase() + value.substring(1).toLowerCase();
      for (final candidate in State.values) {
        if (candidate.label == normalized) return candidate;
      }
      throw FSRSValidationError('Invalid state:[$value]');
    }
    if (value is num) return State.fromValue(value.toInt());
    throw FSRSValidationError('Invalid state:[$value]');
  }

  /// Accepts a [DateTime], epoch milliseconds, or a date string.
  ///
  /// A bare `YYYY-MM-DD` string is read as UTC midnight rather than local
  /// midnight, because that is what `new Date('2022-11-29')` does in
  /// JavaScript and schedules generated by ts-fsrs depend on it.
  static DateTime time(Object? value) {
    if (value is DateTime) return value;
    if (value is String) {
      final parsed = _parseJsDateString(value);
      if (parsed == null) {
        throw FSRSValidationError('Invalid date:[$value]');
      }
      return parsed;
    }
    if (value is num) {
      return DateTime.fromMillisecondsSinceEpoch(value.toInt(), isUtc: true);
    }
    throw FSRSValidationError('Invalid date:[$value]');
  }

  /// Normalizes a review log by copying it and coercing its fields.
  static ReviewLog reviewLog(ReviewLog log) => ReviewLog(
        rating: rating(log.rating),
        state: state(log.state),
        due: time(log.due),
        stability: log.stability,
        difficulty: log.difficulty,
        elapsedDays: log.elapsedDays,
        lastElapsedDays: log.lastElapsedDays,
        scheduledDays: log.scheduledDays,
        learningSteps: log.learningSteps,
        review: time(log.review),
      );

  static final RegExp _dateOnly = RegExp(r'^\d{4}-\d{2}-\d{2}$');

  static DateTime? _parseJsDateString(String value) {
    if (_dateOnly.hasMatch(value)) {
      return DateTime.parse('${value}T00:00:00Z');
    }
    return DateTime.tryParse(value);
  }
}
