// ignore_for_file: depend_on_referenced_packages, file_names

import 'dart:convert';
import 'dart:io';

import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/visitor.dart';
import 'package:analyzer/source/line_info.dart';

/// Regenerates docs/graph-data.json from the repository's Dart sources.
///
/// Run from anywhere with:
///   dart run docs/generate-graph.dart
void main(List<String> arguments) {
  final Directory root = _findRepositoryRoot();
  final _GraphExtractor extractor = _GraphExtractor(root);
  final Map<String, Object> graph = extractor.extract();
  final File output = File(
    '${root.path}${Platform.pathSeparator}docs'
    '${Platform.pathSeparator}graph-data.json',
  );
  output.parent.createSync(recursive: true);
  final String json = const JsonEncoder.withIndent('  ').convert(graph);
  output.writeAsStringSync('$json\n');
  final String compactJson = jsonEncode(graph);
  final File localCompanion = File(
    '${root.path}${Platform.pathSeparator}docs'
    '${Platform.pathSeparator}graph-data.js',
  );
  localCompanion.writeAsStringSync(
    '// Generated by generate-graph.dart. Do not edit.\n'
    'window.__ARCHITECTURE_GRAPH_DATA__ = $compactJson;\n',
  );
  final List<Object?> nodes = graph['nodes']! as List<Object?>;
  final List<Object?> edges = graph['edges']! as List<Object?>;
  stdout.writeln(
    'Wrote ${_relative(root, output)} and '
    '${_relative(root, localCompanion)} with ${nodes.length} nodes and '
    '${edges.length} edges.',
  );
}

Directory _findRepositoryRoot() {
  Directory current = File.fromUri(Platform.script).parent;
  while (true) {
    if (File(
      '${current.path}${Platform.pathSeparator}pubspec.yaml',
    ).existsSync()) {
      return current;
    }
    if (current.parent.path == current.path) {
      throw StateError('Could not find the repository root (pubspec.yaml).');
    }
    current = current.parent;
  }
}

String _relative(Directory root, FileSystemEntity entity) {
  final String rootPath = root.absolute.path.replaceAll('\\', '/');
  return entity.absolute.path
      .replaceAll('\\', '/')
      .replaceFirst('$rootPath/', '');
}

final class _GraphExtractor {
  _GraphExtractor(this.root);

  final Directory root;
  final Map<String, _Node> nodes = <String, _Node>{};
  final List<_Edge> edges = <_Edge>[];
  final Map<String, _ParsedFile> parsedFiles = <String, _ParsedFile>{};
  final Map<String, List<_Callable>> callablesByName =
      <String, List<_Callable>>{};
  final Map<String, List<_ClassInfo>> classesByName =
      <String, List<_ClassInfo>>{};

  Map<String, Object> extract() {
    final List<File> files =
        root
            .listSync(recursive: true, followLinks: false)
            .whereType<File>()
            .where(_shouldScan)
            .toList()
          ..sort(
            (File a, File b) =>
                _relative(root, a).compareTo(_relative(root, b)),
          );

    for (final File file in files) {
      _parseDeclarations(file);
    }
    for (final _ParsedFile file in parsedFiles.values) {
      _extractRelationships(file);
    }

    final Set<String> uniqueEdges = <String>{};
    edges.removeWhere(
      (_Edge edge) => !uniqueEdges.add(
        '${edge.source}\u0000${edge.target}\u0000${edge.type}',
      ),
    );
    for (final _Edge edge in edges) {
      nodes[edge.source]?.fanOut++;
      nodes[edge.target]?.fanIn++;
    }
    for (final _Node node in nodes.values) {
      node.deadCode = node.fanIn == 0 && node.category != 'entrypoint';
    }

    final List<_Node> sortedNodes = nodes.values.toList()
      ..sort((_Node a, _Node b) => a.id.compareTo(b.id));
    edges.sort((_Edge a, _Edge b) {
      final int sourceOrder = a.source.compareTo(b.source);
      if (sourceOrder != 0) return sourceOrder;
      final int targetOrder = a.target.compareTo(b.target);
      if (targetOrder != 0) return targetOrder;
      return a.type.compareTo(b.type);
    });

    return <String, Object>{
      'nodes': sortedNodes.map((_Node node) => node.toJson()).toList(),
      'edges': edges.map((_Edge edge) => edge.toJson()).toList(),
    };
  }

  bool _shouldScan(File file) {
    final String path = _relative(root, file);
    if (!path.endsWith('.dart') || path.endsWith('.g.dart')) return false;
    const Set<String> excluded = <String>{
      '.dart_tool',
      '.git',
      '.idea',
      'anki_source_code',
      'build',
      'docs',
    };
    return !path.split('/').any(excluded.contains);
  }

  void _parseDeclarations(File file) {
    final String relativePath = _relative(root, file);
    final String source = file.readAsStringSync();
    final ParseStringResult result = parseString(
      content: source,
      path: file.absolute.path,
      throwIfDiagnostics: false,
    );
    final String moduleId = _moduleId(relativePath);
    final _ParsedFile parsed = _ParsedFile(
      path: relativePath,
      moduleId: moduleId,
      source: source,
      unit: result.unit,
      lineInfo: result.lineInfo,
    );
    parsedFiles[relativePath] = parsed;
    nodes[moduleId] = _Node(
      id: moduleId,
      label: relativePath.split('/').last.replaceFirst('.dart', ''),
      type: 'module',
      parent: null,
      file: relativePath,
      loc: _sourceLoc(source),
      category: _categoryFor(relativePath, null, isModule: true),
    );

    final _DeclarationVisitor visitor = _DeclarationVisitor(parsed, this);
    result.unit.accept(visitor);
  }

  void _extractRelationships(_ParsedFile file) {
    for (final Directive directive in file.unit.directives) {
      if (directive is! ImportDirective) continue;
      final String uri = directive.uri.stringValue ?? '';
      final String? target = _resolveImport(file.path, uri);
      if (target == null || target == file.moduleId) continue;
      if (!nodes.containsKey(target)) {
        nodes[target] = _Node(
          id: target,
          label: _externalLabel(uri),
          type: 'module',
          parent: null,
          file: uri,
          loc: 0,
          category: 'external',
        );
      }
      edges.add(_Edge(file.moduleId, target, 'imports'));
    }

    for (final _ClassInfo classInfo in file.classes) {
      for (final String superclass in classInfo.superclasses) {
        final _ClassInfo? target = _resolveClass(superclass, file.moduleId);
        if (target != null) {
          edges.add(_Edge(classInfo.id, target.id, 'extends'));
        }
      }
    }

    for (final _Callable callable in file.callables) {
      callable.ast.accept(_CallVisitor(this, file, callable));
    }
  }

  void registerClass(_ClassInfo info) {
    parsedFiles[info.filePath]!.classes.add(info);
    classesByName.putIfAbsent(info.name, () => <_ClassInfo>[]).add(info);
  }

  void registerCallable(_Callable callable) {
    parsedFiles[callable.filePath]!.callables.add(callable);
    callablesByName
        .putIfAbsent(callable.name, () => <_Callable>[])
        .add(callable);
  }

  void addCall(
    _ParsedFile file,
    _Callable caller,
    String name, {
    String? receiver,
  }) {
    final _Callable? callee = _resolveCallable(
      name,
      file.moduleId,
      caller.className,
      receiver,
    );
    if (callee != null && callee.id != caller.id) {
      edges.add(_Edge(caller.id, callee.id, 'calls'));
    }
  }

  _Callable? _resolveCallable(
    String name,
    String moduleId,
    String? callerClass,
    String? receiver,
  ) {
    final List<_Callable> candidates = callablesByName[name] ?? const [];
    if (candidates.isEmpty) return null;

    if (receiver != null) {
      final List<_Callable> receiverMatches = candidates
          .where((_Callable item) => item.className == receiver)
          .toList();
      if (receiverMatches.length == 1) return receiverMatches.single;
    }
    if (callerClass != null) {
      final List<_Callable> sameClass = candidates
          .where(
            (_Callable item) =>
                item.moduleId == moduleId && item.className == callerClass,
          )
          .toList();
      if (sameClass.length == 1) return sameClass.single;
    }
    final List<_Callable> sameModule = candidates
        .where((_Callable item) => item.moduleId == moduleId)
        .toList();
    if (sameModule.length == 1) return sameModule.single;
    return candidates.length == 1 ? candidates.single : null;
  }

  _ClassInfo? _resolveClass(String name, String moduleId) {
    final List<_ClassInfo> candidates = classesByName[name] ?? const [];
    final List<_ClassInfo> sameModule = candidates
        .where((_ClassInfo item) => item.moduleId == moduleId)
        .toList();
    if (sameModule.length == 1) return sameModule.single;
    return candidates.length == 1 ? candidates.single : null;
  }

  String? _resolveImport(String importerPath, String uri) {
    if (uri.startsWith('dart:')) {
      return 'external.${_safeId(uri.substring(5))}';
    }
    if (uri.startsWith('package:')) {
      final String packagePath = uri.substring('package:'.length);
      final int slash = packagePath.indexOf('/');
      final String packageName = slash < 0
          ? packagePath
          : packagePath.substring(0, slash);
      final String rest = slash < 0 ? '' : packagePath.substring(slash + 1);
      if (packageName == 'incremental_reader') {
        return _moduleId('lib/$rest');
      }
      if (packageName == 'fsrs_dart') {
        return _moduleId('fsrs-dart/lib/$rest');
      }
      return 'external.${_safeId(packageName)}';
    }
    if (uri.startsWith('http:') || uri.startsWith('https:')) {
      return 'external.${_safeId(uri)}';
    }
    final Uri resolved = File(
      '${root.path}${Platform.pathSeparator}$importerPath',
    ).parent.uri.resolve(uri);
    final File target = File.fromUri(resolved);
    if (!target.existsSync()) return null;
    return _moduleId(_relative(root, target));
  }

  String _externalLabel(String uri) {
    if (uri.startsWith('package:')) {
      return uri.substring(8).split('/').first;
    }
    if (uri.startsWith('dart:')) return uri.substring(5);
    return uri;
  }
}

final class _DeclarationVisitor extends RecursiveAstVisitor<void> {
  _DeclarationVisitor(this.file, this.extractor);

  final _ParsedFile file;
  final _GraphExtractor extractor;
  String? _className;

  @override
  void visitClassDeclaration(ClassDeclaration node) {
    final String name = node.namePart.typeName.lexeme;
    _registerClass(name, node, <String>[
      if (node.extendsClause case final ExtendsClause clause)
        clause.superclass.name.lexeme,
      if (node.withClause case final WithClause clause)
        ...clause.mixinTypes.map((NamedType type) => type.name.lexeme),
      if (node.implementsClause case final ImplementsClause clause)
        ...clause.interfaces.map((NamedType type) => type.name.lexeme),
    ]);
    final String? previous = _className;
    _className = name;
    super.visitClassDeclaration(node);
    _className = previous;
  }

  @override
  void visitEnumDeclaration(EnumDeclaration node) {
    final String name = node.namePart.typeName.lexeme;
    _registerClass(name, node, const <String>[]);
    final String? previous = _className;
    _className = name;
    super.visitEnumDeclaration(node);
    _className = previous;
  }

  @override
  void visitMixinDeclaration(MixinDeclaration node) {
    final String name = node.name.lexeme;
    _registerClass(name, node, <String>[
      if (node.implementsClause case final ImplementsClause clause)
        ...clause.interfaces.map((NamedType type) => type.name.lexeme),
    ]);
    final String? previous = _className;
    _className = name;
    super.visitMixinDeclaration(node);
    _className = previous;
  }

  @override
  void visitExtensionDeclaration(ExtensionDeclaration node) {
    final String name =
        node.name?.lexeme ??
        'extension_${file.lineInfo.getLocation(node.offset).lineNumber}';
    _registerClass(name, node, const <String>[]);
    final String? previous = _className;
    _className = name;
    super.visitExtensionDeclaration(node);
    _className = previous;
  }

  @override
  void visitFunctionDeclaration(FunctionDeclaration node) {
    _registerCallable(node.name.lexeme, node, className: null);
    // Do not recurse into local functions; each top-level function owns its
    // call graph and local closures are deliberately folded into it.
  }

  @override
  void visitMethodDeclaration(MethodDeclaration node) {
    final String name = node.name.lexeme;
    final String idName = node.isSetter
        ? '$name.set'
        : node.isGetter
        ? '$name.get'
        : node.isOperator
        ? _operatorId(name)
        : name;
    _registerCallable(
      node.isSetter ? '$name=' : name,
      node,
      className: _className,
      idName: idName,
    );
  }

  @override
  void visitConstructorDeclaration(ConstructorDeclaration node) {
    final String className = _className ?? 'constructor';
    final String suffix = node.name?.lexeme ?? 'new';
    final String lookupName = node.name == null
        ? className
        : '$className.${node.name!.lexeme}';
    _registerCallable(
      '$className.$suffix',
      node,
      className: className,
      lookupName: lookupName,
    );
  }

  void _registerClass(String name, AstNode ast, List<String> superclasses) {
    final String id = '${file.moduleId}.${_safeId(name)}';
    extractor.nodes[id] = _Node(
      id: id,
      label: name,
      type: 'class',
      parent: file.moduleId,
      file: file.path,
      loc: _nodeLoc(file, ast),
      category: _categoryFor(file.path, name),
    );
    extractor.registerClass(
      _ClassInfo(
        id: id,
        name: name,
        moduleId: file.moduleId,
        filePath: file.path,
        superclasses: superclasses,
      ),
    );
  }

  void _registerCallable(
    String displayName,
    AstNode ast, {
    required String? className,
    String? lookupName,
    String? idName,
  }) {
    final String label = displayName.split('.').last;
    final String qualified = className == null
        ? _safeId(idName ?? displayName)
        : '${_safeId(className)}.${_safeId(idName ?? label)}';
    String id = '${file.moduleId}.$qualified';
    var duplicate = 2;
    while (extractor.nodes.containsKey(id)) {
      id = '${file.moduleId}.$qualified.overload$duplicate';
      duplicate++;
    }
    final String category = _categoryFor(
      file.path,
      label,
      isEntrypoint: _isEntrypoint(file.path, label, className),
    );
    extractor.nodes[id] = _Node(
      id: id,
      label: label,
      type: 'function',
      parent: file.moduleId,
      file: file.path,
      loc: _nodeLoc(file, ast),
      category: category,
    );
    extractor.registerCallable(
      _Callable(
        id: id,
        name: lookupName ?? label,
        moduleId: file.moduleId,
        filePath: file.path,
        className: className,
        ast: ast,
      ),
    );
  }
}

final class _CallVisitor extends RecursiveAstVisitor<void> {
  _CallVisitor(this.extractor, this.file, this.caller);

  final _GraphExtractor extractor;
  final _ParsedFile file;
  final _Callable caller;

  @override
  void visitMethodInvocation(MethodInvocation node) {
    String? receiver;
    final Expression? target = node.target;
    if (target is SimpleIdentifier) receiver = target.name;
    extractor.addCall(file, caller, node.methodName.name, receiver: receiver);
    super.visitMethodInvocation(node);
  }

  @override
  void visitInstanceCreationExpression(InstanceCreationExpression node) {
    final String className = node.constructorName.type.name.lexeme;
    final String name = node.constructorName.name == null
        ? className
        : '$className.${node.constructorName.name!.name}';
    extractor.addCall(file, caller, name, receiver: className);
    super.visitInstanceCreationExpression(node);
  }

  @override
  void visitFunctionExpressionInvocation(FunctionExpressionInvocation node) {
    final Expression function = node.function;
    if (function is SimpleIdentifier) {
      extractor.addCall(file, caller, function.name);
    }
    super.visitFunctionExpressionInvocation(node);
  }
}

final class _ParsedFile {
  _ParsedFile({
    required this.path,
    required this.moduleId,
    required this.source,
    required this.unit,
    required this.lineInfo,
  });

  final String path;
  final String moduleId;
  final String source;
  final CompilationUnit unit;
  final LineInfo lineInfo;
  final List<_Callable> callables = <_Callable>[];
  final List<_ClassInfo> classes = <_ClassInfo>[];
}

final class _Callable {
  _Callable({
    required this.id,
    required this.name,
    required this.moduleId,
    required this.filePath,
    required this.className,
    required this.ast,
  });

  final String id;
  final String name;
  final String moduleId;
  final String filePath;
  final String? className;
  final AstNode ast;
}

final class _ClassInfo {
  _ClassInfo({
    required this.id,
    required this.name,
    required this.moduleId,
    required this.filePath,
    required this.superclasses,
  });

  final String id;
  final String name;
  final String moduleId;
  final String filePath;
  final List<String> superclasses;
}

final class _Node {
  _Node({
    required this.id,
    required this.label,
    required this.type,
    required this.parent,
    required this.file,
    required this.loc,
    required this.category,
  });

  final String id;
  final String label;
  final String type;
  final String? parent;
  final String file;
  final int loc;
  final String category;
  int fanIn = 0;
  int fanOut = 0;
  bool deadCode = false;

  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'label': label,
    'type': type,
    'parent': parent,
    'file': file,
    'loc': loc,
    'category': category,
    'fanIn': fanIn,
    'fanOut': fanOut,
    if (deadCode) 'deadCode': true,
  };
}

final class _Edge {
  _Edge(this.source, this.target, this.type);

  final String source;
  final String target;
  final String type;

  Map<String, String> toJson() => <String, String>{
    'source': source,
    'target': target,
    'type': type,
  };
}

String _moduleId(String relativePath) {
  String path = relativePath.replaceAll('\\', '/').replaceFirst('.dart', '');
  if (path.startsWith('lib/')) path = path.substring(4);
  return path.split('/').map(_safeId).join('.');
}

String _safeId(String value) {
  if (value == '_') return 'private';
  final String id = value
      .replaceAll(RegExp(r'[^A-Za-z0-9_]+'), '_')
      .replaceAll(RegExp(r'_+'), '_')
      .replaceAll(RegExp(r'^_|_$'), '');
  return id.isEmpty ? 'symbol' : id;
}

String _operatorId(String value) => switch (value) {
  '==' => 'operator_equals',
  '<' => 'operator_less_than',
  '<=' => 'operator_less_than_or_equal',
  '>' => 'operator_greater_than',
  '>=' => 'operator_greater_than_or_equal',
  '+' => 'operator_add',
  '-' => 'operator_subtract',
  '*' => 'operator_multiply',
  '/' => 'operator_divide',
  '~/' => 'operator_integer_divide',
  '%' => 'operator_modulo',
  '[]' => 'operator_index',
  '[]=' => 'operator_index_set',
  '~' => 'operator_bitwise_not',
  '&' => 'operator_bitwise_and',
  '|' => 'operator_bitwise_or',
  '^' => 'operator_bitwise_xor',
  '<<' => 'operator_shift_left',
  '>>' => 'operator_shift_right',
  '>>>' => 'operator_unsigned_shift_right',
  _ => 'operator_${_safeId(value)}',
};

int _sourceLoc(String source) =>
    source.isEmpty ? 0 : '\n'.allMatches(source).length + 1;

int _nodeLoc(_ParsedFile file, AstNode node) {
  final int start = file.lineInfo.getLocation(node.offset).lineNumber;
  final int end = file.lineInfo.getLocation(node.end).lineNumber;
  return end - start + 1;
}

bool _isEntrypoint(String path, String name, String? className) {
  if (name == 'main') return true;
  if (RegExp(r'^(on|handle)[A-Z_]').hasMatch(name)) return true;
  if (<String>{
    'initState',
    'didChangeDependencies',
    'didUpdateWidget',
  }.contains(name)) {
    return true;
  }
  if (name == 'build' &&
      className != null &&
      (path.contains('/features/') || path.contains('_screen.dart'))) {
    return true;
  }
  return false;
}

String _categoryFor(
  String path,
  String? name, {
  bool isModule = false,
  bool isEntrypoint = false,
}) {
  final String lowerPath = path.toLowerCase();
  final String lowerName = (name ?? '').toLowerCase();
  if (isEntrypoint ||
      lowerPath.endsWith('/main.dart') ||
      path == 'lib/main.dart') {
    return 'entrypoint';
  }
  if (lowerPath.contains('/storage/') ||
      lowerPath.contains('database') ||
      lowerName.contains('repository') ||
      lowerName.contains('database')) {
    return 'db';
  }
  if (lowerPath.contains('/features/') ||
      lowerPath.contains('screen.dart') ||
      lowerPath.contains('route')) {
    return 'route';
  }
  if (lowerPath.contains('/shared/') ||
      lowerPath.contains('/util') ||
      lowerPath.contains('/platform/') ||
      lowerName.contains('helper') ||
      lowerName.contains('util')) {
    return 'util';
  }
  return 'other';
}
